### Login ellenőrzése. Sikeres.
POST http://localhost:8003/api HTTP/1.1
content-type: application/json

{ "action": "login", "uid": "admin", "password": "admin" }

### Felhasználók betöltése.
POST http://localhost:8003/api HTTP/1.1
content-type: application/json

{ "action": "loadusers" }